# Generated by Django 3.1.3 on 2020-12-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=30)),
                ('cost', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
